"""add scan_logs

Revision ID: a3f1c9d24e70
Revises: e05dd83fbbf3
Create Date: 2026-09-21 10:00:00.000000

SRS 6.2 ScanLog. Written by hand rather than autogenerated, to avoid pointing
autogenerate at the live database; checked against Base.metadata in
tests/test_migrations.py.

There is no image column. See app/db/models/scan_log.py and CON-001.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'a3f1c9d24e70'
down_revision: Union[str, Sequence[str], None] = 'e05dd83fbbf3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


JSONType = postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite')


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table('scan_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_auth_id', sa.String(length=255), nullable=False),
    sa.Column('outcome', sa.Enum('ROUTINE', 'REFERRAL', 'UNUSABLE', 'ERROR', name='scan_outcome'), nullable=False),
    sa.Column('concerns', JSONType, nullable=True),
    sa.Column('clinical_signals', JSONType, nullable=True),
    sa.Column('displayed_associations', JSONType, nullable=True),
    sa.Column('suppression_reasons', JSONType, nullable=True),
    sa.Column('discards', JSONType, nullable=True),
    sa.Column('matrix_version', sa.String(length=32), nullable=False),
    sa.Column('analysis_backend', sa.Enum('INTERNAL_MODEL', 'HOSTED_PROVIDER', name='analysis_backend'), nullable=True),
    sa.Column('routing', JSONType, nullable=True),
    sa.Column('model_versions', JSONType, nullable=True),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('quota_decremented', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_auth_id'], ['users.auth_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scan_logs_user_auth_id'), 'scan_logs', ['user_auth_id'], unique=False)
    op.create_index(op.f('ix_scan_logs_idempotency_key'), 'scan_logs', ['idempotency_key'], unique=False)
    op.create_index(op.f('ix_scan_logs_created_at'), 'scan_logs', ['created_at'], unique=False)


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index(op.f('ix_scan_logs_created_at'), table_name='scan_logs')
    op.drop_index(op.f('ix_scan_logs_idempotency_key'), table_name='scan_logs')
    op.drop_index(op.f('ix_scan_logs_user_auth_id'), table_name='scan_logs')
    op.drop_table('scan_logs')
    sa.Enum(name='analysis_backend').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='scan_outcome').drop(op.get_bind(), checkfirst=True)
