"""create users and safety_answer_changes

Revision ID: cba56951400a
Revises: 
Create Date: 2026-09-05 13:18:23.950418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cba56951400a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('auth_id', sa.String(length=255), nullable=False),
    sa.Column('auth_provider', sa.String(length=32), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('dob_confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('age_band', sa.Enum('MINOR', 'ADULT', name='age_band'), nullable=True),
    sa.Column('scan_access_blocked', sa.Boolean(), nullable=False),
    sa.Column('is_pregnant', sa.Boolean(), nullable=False),
    sa.Column('on_prescription_treatment', sa.Boolean(), nullable=False),
    sa.Column('referral_flag', sa.Boolean(), nullable=False),
    sa.Column('safety_answers_completed', sa.Boolean(), nullable=False),
    sa.Column('skin_type', sa.Enum('OILY', 'DRY', 'COMBINATION', 'NORMAL', name='skin_type'), nullable=True),
    sa.Column('skin_type_set_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consent_version', sa.String(length=32), nullable=True),
    sa.Column('consent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('subscription_tier', sa.Enum('FREE', 'LIMITED', 'PREMIUM', name='subscription_tier'), nullable=False),
    sa.Column('scans_remaining', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_sign_in_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('auth_id')
    )
    op.create_table('safety_answer_changes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_auth_id', sa.String(length=255), nullable=False),
    sa.Column('previous_answers', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('new_answers', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('referral_flag_before', sa.Boolean(), nullable=True),
    sa.Column('referral_flag_after', sa.Boolean(), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_auth_id'], ['users.auth_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_safety_answer_changes_user_auth_id'), 'safety_answer_changes', ['user_auth_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_safety_answer_changes_user_auth_id'), table_name='safety_answer_changes')
    op.drop_table('safety_answer_changes')
    op.drop_table('users')
    # ### end Alembic commands ###
