"""add review_records

Revision ID: e05dd83fbbf3
Revises: cba56951400a
Create Date: 2026-09-05 19:16:48.651547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e05dd83fbbf3'
down_revision: Union[str, Sequence[str], None] = 'cba56951400a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('reviewer_name', sa.String(length=200), nullable=False),
    sa.Column('licence_number', sa.String(length=100), nullable=False),
    sa.Column('reviewed_at', sa.Date(), nullable=False),
    sa.Column('matrix_version', sa.String(length=32), nullable=False),
    sa.Column('catalogue_version', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_records_matrix_version'), 'review_records', ['matrix_version'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_review_records_matrix_version'), table_name='review_records')
    op.drop_table('review_records')
    # ### end Alembic commands ###
